package com.wtbuddy.wtbuddy.enums;

public enum NotificationType {
    FRIEND_REQUEST,
    FRIEND_ACCEPTED,
    EVENT_INVITE,
    MATCH_SUGGESTION,
    EVENT_REMINDER,
    TRIP_INVITE,
    TRIP_JOIN_REQUEST,
    TRIP_JOIN_ACCEPTED,
    TRIP_JOIN_DECLINED,
    EVENT_JOIN_REQUEST,
    EVENT_JOIN_ACCEPTED,
    EVENT_JOIN_DECLINED
}